# Generated by Django 4.2.29 on 2026-05-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255, verbose_name='Donor Full Name')),
                ('donor_email', models.EmailField(max_length=254, verbose_name='Donor Email Address')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount in USD ($)')),
                ('amount_inr', models.DecimalField(decimal_places=2, help_text='Converted automatically from USD', max_digits=12, verbose_name='Amount in Rupees (₹)')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=83.5, max_digits=6, verbose_name='USD to INR Exchange Rate')),
                ('frequency', models.CharField(choices=[('One-time', 'One-time'), ('Monthly', 'Monthly Support')], default='One-time', max_length=20, verbose_name='Donation Frequency')),
                ('campaign', models.CharField(choices=[('general', 'General Needs (Where it is needed most)'), ('water', 'Clean Drinking Water Wells'), ('education', 'Books & Classrooms Fund'), ('medical', 'Mobile Health Clinics')], default='general', max_length=50, verbose_name='Direct Donation To')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency')], default='card', max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed (Received)'), ('Failed', 'Failed')], default='Completed', max_length=20, verbose_name='Donation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Donation Date')),
            ],
            options={
                'verbose_name': 'Cash Donation',
                'verbose_name_plural': 'Cash Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255, verbose_name='Donor Name')),
                ('donor_email', models.EmailField(max_length=254, verbose_name='Donor Email')),
                ('donor_phone', models.CharField(max_length=20, verbose_name='Donor Contact Number')),
                ('product_category', models.CharField(choices=[('book', 'Books & Stationery'), ('food', 'Food & Groceries'), ('clothes', 'Clothes & Apparel'), ('furniture', 'Furniture & Household'), ('machine', 'Machines & Electronic Appliances'), ('other', 'Other Products')], default='other', max_length=20, verbose_name='Product Category')),
                ('product_name', models.CharField(help_text="e.g. 'Science textbooks', 'Winter jackets'", max_length=255, verbose_name='Product Name / Title')),
                ('product_description', models.TextField(blank=True, help_text='List details, quantities, and condition notes', verbose_name='Product Description & Quantity')),
                ('product_condition', models.CharField(choices=[('New', 'Brand New / Sealed'), ('Like New', 'Like New / Barely Used'), ('Good', 'Good / Fully Functional'), ('Fair', 'Fair / Needs minor cleanup'), ('Poor', 'Poor / Needs repair')], default='Good', max_length=20, verbose_name='Condition')),
                ('pickup_address', models.TextField(verbose_name='Collection / Pickup Address')),
                ('pickup_time_preference', models.CharField(blank=True, help_text="e.g. 'Weekends morning', 'Any weekday after 5 PM'", max_length=255, verbose_name='Preferred Pickup Day/Time')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Scheduled', 'Pickup Scheduled'), ('Collected', 'Product Collected'), ('Completed', 'Distributed / Completed'), ('Cancelled', 'Cancelled / Declined')], default='Pending', max_length=20, verbose_name='Pickup / Distribution Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for scheduling, driver names, or distribution logs', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
            ],
            options={
                'verbose_name': 'Product Donation Request',
                'verbose_name_plural': 'Product Donation Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
