# Generated by Django 4.2.29 on 2026-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdonation',
            name='amount_inr',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount in Rupees (₹)'),
        ),
        migrations.AlterField(
            model_name='cashdonation',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount in USD ($)'),
        ),
        migrations.AlterField(
            model_name='cashdonation',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='USD to INR Exchange Rate'),
        ),
    ]
