# Generated by Django 4.2.29 on 2026-05-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_cashdonation_amount_inr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdonation',
            name='transaction_reference_id',
            field=models.CharField(blank=True, help_text='For UPI Reference ID or card transaction ID', max_length=100, null=True, verbose_name='Transaction Reference ID'),
        ),
        migrations.AlterField(
            model_name='cashdonation',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('upi', 'UPI Payment')], default='card', max_length=20, verbose_name='Payment Method'),
        ),
    ]
