# Generated by Django 4.2.29 on 2026-05-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_cashdonation_transaction_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdonation',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='cashdonation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Completed', 'Completed (Received)'), ('Failed', 'Failed')], default='Completed', max_length=20, verbose_name='Donation Status'),
        ),
    ]
