# Generated by Django 4.2.29 on 2026-05-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_cashdonation_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255, verbose_name='Sender Name')),
                ('donor_email', models.EmailField(max_length=254, verbose_name='Sender Email')),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sender Phone (Optional)')),
                ('subject', models.CharField(choices=[('donation', 'Donation & Tax Invoice Help'), ('volunteer', 'Volunteering Opportunities'), ('partnership', 'Corporate Partnerships'), ('media', 'Media & PR Inquiries'), ('other', 'General Questions')], default='other', max_length=50, verbose_name='Subject of Inquiry')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received Date')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
